version: '3'
services:
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    restart: always
  backend:
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/movie_rank_chart
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    tty: true
    restart: always
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    tty: true
    restart: always